name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest
    env:
      TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@shayonpal'
          always-auth: true

      - name: Upgrade npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Verify package version matches tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "Tag version $TAG_VERSION does not match package.json version $PKG_VERSION"
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        env:
          NPM_CONFIG_PROVENANCE: 'true'
        run: npm publish --access public
